### ISSUE TITLE
conversion stuck / serious performance problem / incorrect logging??

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-client#6]
I tried to convert dnb artifacts see config below. however after more than 13 cpu hours it seems still converting the first file - a tiny gz ttl file ?
```
http://dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=name.ttl.gz
http://dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=geografikum.ttl.gz
http://dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=koerperschaft.ttl.gz
http://dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=kongress.ttl.gz
http://dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=person.ttl.gz
http://dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=sachbegriff.ttl.gz
http://dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=werk.ttl.gz

--------------------------------------------------------

Converter:

input file:             /opt/databus-client/tempdir_downloaded_files/dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=sachbegriff.ttl.gz
converted file: /var/repo/jj-author/dnb/authorities/2019.06.13/authorities_type=sachbegriff.nt.bz2


```
![image](https://user-images.githubusercontent.com/2630603/67044801-5e559480-f12d-11e9-9d64-8faab43e32b9.png)

performance compared on my laptop with rapper

```
time zcat authorities_type\=sachbegriff.ttl.gz | rapper -i turtle - urn:base -o ntriples > converted.nt
rapper: Parsing file <stdin> with parser turtle and base URI urn:base
rapper: Serializing with serializer ntriples and base URI urn:base
rapper: Parsing returned 2518628 triples

real	0m10.776s
user	0m10.156s
sys	0m0.460s
```

=======
CONFIG

```
mkdir -p repo
cd repo

echo "
PREFIX dataid: <http://dataid.dbpedia.org/ns/core#>
PREFIX dataid-cv: <http://dataid.dbpedia.org/ns/cv#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>

# Get all files
SELECT DISTINCT ?file WHERE {
        ?dataset dataid:artifact <https://databus.dbpedia.org/jj-author/dnb/authorities> .
        ?dataset dcat:distribution ?distribution .
        {
                ?distribution dct:hasVersion ?latestVersion 
                {
        SELECT (?version as ?latestVersion) WHERE { 
                ?dataset dataid:artifact <https://databus.dbpedia.org/jj-author/dnb/authorities> . 
                ?dataset dct:hasVersion ?version . 
        } ORDER BY DESC (?version) LIMIT 1 
                } 
        }
        ?distribution dcat:downloadURL ?file .
}
" > query

docker run --name databus-client-dnb \
    -v $(pwd)/query:/opt/databus-client/query \
    -v $(pwd):/var/repo \
    -e FORMAT="nt" \
    -e COMPRESSION="bz2" \
    dbpedia/databus-client

docker rm databus-client-dnb

```

is the logging correct (maybe it already started another file without logging that?)

**Comment by JJ-Author** [comment]
it is impossible to understand what is happening therefore I opened also https://github.com/dbpedia/databus-client/issues/7

**Comment by JJ-Author** [comment]
finally crashed 

```
Converter:                                                                                                                                                                                                  
                                                                                                                                                                                                            
input file:             /opt/databus-client/tempdir_downloaded_files/dbpedia-mappings.tib.eu/databus-repo/jj-author/dnb/authorities/2019.06.13/authorities_type=sachbegriff.ttl.gz                          
converted file: /var/repo/jj-author/dnb/authorities/2019.06.13/authorities_type=sachbegriff.nt.bz2                                                                                                          

^Exception in thread "RemoteBlock-temp-file-clean-thread" java.lang.OutOfMemoryError: Java heap space
        at org.apache.spark.storage.BlockManager$RemoteBlockDownloadFileManager.org$apache$spark$storage$BlockManager$RemoteBlockDownloadFileManager$$keepCleaning(BlockManager.scala:1726)
        at org.apache.spark.storage.BlockManager$RemoteBlockDownloadFileManager$$anon$2.run(BlockManager.scala:1692)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
        at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.lang.Integer.valueOf(Integer.java:832)
        at scala.runtime.BoxesRunTime.boxToInteger(BoxesRunTime.java:65)
        at scala.collection.IndexedSeqOptimized$class.zipWithIndex(IndexedSeqOptimized.scala:103)
        at scala.collection.mutable.ArrayOps$ofRef.zipWithIndex(ArrayOps.scala:186)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:254)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
        at org.apache.spark.SparkContext$$anonfun$union$1$$anonfun$31.apply(SparkContext.scala:1314)
        at org.apache.spark.SparkContext$$anonfun$union$1$$anonfun$31.apply(SparkContext.scala:1314)
        at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:248)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
        at org.apache.spark.SparkContext$$anonfun$union$1.apply(SparkContext.scala:1314)
        at org.apache.spark.SparkContext$$anonfun$union$1.apply(SparkContext.scala:1313)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.SparkContext.withScope(SparkContext.scala:699)
        at org.apache.spark.SparkContext.union(SparkContext.scala:1313)
        at org.apache.spark.SparkContext$$anonfun$union$2.apply(SparkContext.scala:1325)
        at org.apache.spark.SparkContext$$anonfun$union$2.apply(SparkContext.scala:1325)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.SparkContext.withScope(SparkContext.scala:699)
        at org.apache.spark.SparkContext.union(SparkContext.scala:1324)
        at org.dbpedia.databus.rdf_reader.TTL_Reader$.readTTL(TTL_Reader.scala:45)
        at org.dbpedia.databus.Converter$.convertFormat(Converter.scala:63)
        at org.dbpedia.databus.FileHandler$.convertFile(FileHandler.scala:53)
        at org.dbpedia.databus.main.Main_DownloadAndConvert$$anonfun$main$1.apply(Main_DownloadAndConvert.scala:58)
        at org.dbpedia.databus.main.Main_DownloadAndConvert$$anonfun$main$1.apply(Main_DownloadAndConvert.scala:54)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:05 h
[INFO] Finished at: 2019-10-17T23:54:00Z
[INFO] ------------------------------------------------------------------------

```

**Comment by JJ-Author** [comment]
i actually wonder how 32 GiB of resident RAM data can not be enough for spark, what about spill to disk? @Vehnem you have probably more experience with spark than @Eisenbahnplatte.

**Comment by Vehnem** [comment]
Yes, 32GB could be possible not enough for SANSA, but i will configure spill to disk and choose another Serialization.
